resources:
- name: platform-automation-tasks-s3
  type: s3
  source:
    access_key_id: ((s3_access_key))
    secret_access_key: ((s3_secret_access_key))
    bucket: bucc
    regexp: platform-automation-tasks-(.*).zip
    endpoint: https://storage.googleapis.com

- name: platform-automation-image-s3
  type: s3
  source:
    access_key_id: ((s3_access_key))
    secret_access_key: ((s3_secret_access_key))
    bucket: bucc
    regexp: platform-automation-image-(.*).tgz
    endpoint: https://storage.googleapis.com

- name: test-interpolation-task-src
  type: git
  source:
    uri: https://github.com/Pivotal-Field-Engineering/bucc-bootstrap-automation

jobs:
- name: test-resources
  plan:
  - aggregate:
    - get: platform-automation-tasks-s3
      params:
        unpack: true
    - get: platform-automation-image-s3
      params:
        unpack: true
    - get: test-interpolation-task-src

  ####
  # Move the subdirectories from the git checkout to a place where Concourse
  # can make them available to the test-interpolate task.
  #
  # Note: the image is specified since the base container image has no bash
  ####
  - task: prepare-inputs
    image: platform-automation-image-s3
    config:
      platform: linux
      inputs:
        - name: test-interpolation-task-src
      outputs:
        - name: config
        - name: vars
      run:
        path: bash
        args:
          - "-c"
          - |
            mv test-interpolation-task-src/config/* config/
            mv test-interpolation-task-src/vars/* vars/

  - task: test-interpolate
    image: platform-automation-image-s3
    file: test-interpolation-task-src/test-interpolation-task-src/test-task.yml
    params:
      VARS_FILES: vars/vars.yml
